apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
    release: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
