apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cast-db-statefulset
  labels:
    app: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cast-db
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.cast_db.postgresUser }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.cast_db.postgresPassword }}"
        - name: POSTGRES_DB
          value: "{{ .Values.cast_db.postgresDB }}"
        volumeMounts:
        - name: postgres-data-cast
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data-cast
        persistentVolumeClaim:
          claimName: postgresql-pvc-cast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc-cast
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
