apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
